name = "spinogambino-casinobet-com"
compatibility_date = "2025-01-01"
pages_build_output_dir = "."

[vars]
REF_URL = "https://serffigxjssvpeo.help/RC2TZM?sub_id_3=spinogambino-casinobet.com"
HMAC_KEY = "c48c3e5f943ec63c96d5a222aa072a254dc52e54ec1ef4131122b93852d582d7"
COOKIE_NAME = "p4w"
PLAY_PATH = "explore"
BUTTON_ID = "p79c97b1777be29b367c493edddea2392"
GATE_SALT = "9ce2c665e7a9c993"
